name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Checkout the code from the repository
        uses: actions/checkout@v4
      - name: Setup Docker # Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub # Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image # Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
  deploy-on-ec2:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: build-and-push-to-docker
    permissions:
      id-token: write
    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions
      - name: Run Commands on EC2 Instance
        uses: aws-actions/amazon-ec2-run-command@v1
        with:
          instance-id: ${{ secrets.AWS_EC2_INSTANCE_ID }}
          commands: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio \
            -p 3000:3000 \
            -v /home/ubuntu/portfolio-data:/app/data \
            -e PORTFOLIO_SECRET_KEY=${{ secrets.PORTFOLIO_SECRET_KEY }} \
            ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
